name: intheloopapp
version: 1.1.22+32
publish_to: none
description: Mobile app for Tapped.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  algolia: ^1.0.1
  animations: ^2.0.1
  bloc: ^8.1.0
  bloc_test: ^9.1.0
  cached_network_image: ^3.1.0
  cloud_firestore: ^4.3.1
  cloud_functions: ^4.0.7
  connectivity_plus: ^3.0.2
  crypto: ^3.0.1
  cupertino_icons: ^1.0.3
  enum_to_string: ^2.0.1
  equatable: ^2.0.3
  file_picker: ^5.0.1
  firebase_analytics: ^10.1.0
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  firebase_core_platform_interface: ^4.5.2
  firebase_crashlytics: ^3.0.9
  firebase_dynamic_links: ^5.0.11
  firebase_messaging: ^14.2.1
  firebase_remote_config: ^3.0.9
  firebase_storage: ^11.0.10
  flutter: 
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_cache_manager: ^3.1.2
  flutter_image_compress: ^1.0.0
  flutter_native_splash: ^2.2.9
  flutter_slidable: ^2.0.0
  flutter_spinkit: ^5.0.0
  flutter_stripe: ^9.0.0+1
  flutter_svg: ^1.0.1
  font_awesome_flutter: ^10.2.1
  formz: ^0.5.0+1
  google_sign_in: ^6.0.1
  hydrated_bloc: ^9.0.0
  image_picker: ^0.8.2
  intl: ^0.17.0
  json_annotation: ^4.5.0
  just_audio: ^0.9.2
  package_info_plus: ^3.0.2
  path_provider: ^2.0.2
  quiver: ^3.0.1
  rxdart: ^0.27.5
  share_plus: ^4.0.1
  sign_in_with_apple: ^4.1.0
  skeleton_animation: ^0.1.4
  skeleton_text: ^3.0.0
  skeletons: ^0.0.3
  stream_chat_flutter: ^5.2.0
  timeago: ^3.1.0
  url_launcher: ^6.0.9
  uuid: ^3.0.4

dev_dependencies: 
  build_runner: ^2.0.6
  flutter_launcher_icons: ^0.12.0
  flutter_lints: ^2.0.1
  flutter_test: 
    sdk: flutter
  json_serializable: ^6.3.1
  mockito: ^5.0.16
  pubspec_dependency_sorter: ^1.0.3
  very_good_analysis: ^4.0.0+1

flutter_icons: 
  image_path_ios: assets/app_icon_ios.png
  image_path_android: assets/app_icon_ios.png
  android: true
  ios: true
  remove_alpha_ios: true

flutter: 
  assets: 
    - assets/
  uses-material-design: true
