
final List<String> labels = [
  'Independent',
  'Death Row Records',
  'Blank Kanvaz',
  'Playmakr Entertainment',
  'Universal Music Group',
  'Sony Music Entertainment',
  'Warner Music Group',
  'EMI Group',
  'BMG',
  'Atlantic Records',
  'Interscope Geffen A&M',
  'Island Records',
  'Republic Records',
  'Columbia Records',
  'RCA Records',
  'Capitol Music Group',
  'Def Jam Recordings',
  'Epic Records',
  'Virgin Records',
  'None',
];
