
final List<String> occupations = [
  'Artist',
  'DJ',
  'Music Producer',
  'Recording Engineer',
  'Audio Engineer',
  'Sound Designer',
  'Music Director',
  'A&R Coordinator',
  'Music Supervisor',
  'Tour Manager',
  'Booking Agent',
  'Concert Promoter',
  'Public Relations Specialist',
  'Music Publicist',
  'Social Media Manager',
  'Music Journalist',
  'Music Critic',
  'Artist Manager',
  'Music Teacher',
  'Session Musician',
  'Composer',
  'Arranger',
  'Songwriter',
  'Music Therapist',
  'Music Librarian',
  'Music Licensing Coordinator',
  'Music Publisher',
  'Music Editor',
  'Music Video Director',
  'Radio DJ',
  'Radio Producer',
  'Radio Promotions Director',
  'Music Retail Store Manager',
  'Instrument Technician',
  'Road Crew Technician',
  'Sound Technician',
  'Live Sound Engineer',
  'Lighting Designer',
  'Stage Manager',
  'Merchandise Coordinator',
  'Talent Scout',
  'Record Label Executive',
  'Other',
];
